// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateOrderByDetailsOperation OperationName = "CreateOrderByDetails"
	DeleteOrderByDetailsOperation OperationName = "DeleteOrderByDetails"
	GetOrderByIdOperation         OperationName = "GetOrderById"
	PayOrderOperation             OperationName = "PayOrder"
)
