// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateOrderByDetails implements CreateOrderByDetails operation.
//
// Создание заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrderByDetails(ctx context.Context, req *CreateOrderRequest) (r CreateOrderByDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrderByDetails implements deleteOrderByDetails operation.
//
// Создание заказа.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) DeleteOrderByDetails(ctx context.Context, params DeleteOrderByDetailsParams) (r DeleteOrderByDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderById implements GetOrderById operation.
//
// Get order data by id.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
