// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateOrderByDetails implements CreateOrderByDetails operation.
	//
	// Создание заказа.
	//
	// POST /api/v1/orders
	CreateOrderByDetails(ctx context.Context, req *CreateOrderRequest) (CreateOrderByDetailsRes, error)
	// DeleteOrderByDetails implements deleteOrderByDetails operation.
	//
	// Создание заказа.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	DeleteOrderByDetails(ctx context.Context, params DeleteOrderByDetailsParams) (DeleteOrderByDetailsRes, error)
	// GetOrderById implements GetOrderById operation.
	//
	// Get order data by id.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Оплата заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
