// Code generated by ogen, DO NOT EDIT.
package order_v1

type CreateOrderByDetailsRes interface {
	createOrderByDetailsRes()
}

type DeleteOrderByDetailsRes interface {
	deleteOrderByDetailsRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type PayOrderRes interface {
	payOrderRes()
}
